# Docspine standard targets
# See: https://nondualworks.github.io/docspine/reference/manifest-schema/

docs-build:
    mkdocs build --site-dir site

docs-serve:
    mkdocs serve --dev-addr 0.0.0.0:8000

docs-check:
    mkdocs build --strict --site-dir site
